### ISSUE TITLE
Add get_headers method to BaseSignature

### ISSUE THREAD

**Issue by sggottlieb** [sggottlieb/cmfieldguide#1]
Should return a dictionary of headers.  

You can use httplib2.  See here:

http://stackoverflow.com/questions/843392/python-get-http-headers-from-urllib-call

I have added httplib2 to the req.txt

**Comment by deanebarker** [comment]
I don't think we need this.  If we concentrate all calls for pages through get_page to facilitate caching (see other issue), then you can get headers like this:

```
get_page(url).headers
```

**Comment by sggottlieb** [comment]
Sounds good to me.
