### ISSUE TITLE
EPiServer is returning a false positive on Ektron.com

### ISSUE THREAD

**Issue by sggottlieb** [sggottlieb/cmfieldguide#15]
The issue is that the test is not looking for a login form.  Instead, it is just seeing if there is a page.  The Ektron 404 page just happens to return a status code of 200.  Go figure.  I would check the contents of the page and see if there is something that looks like the EPiServer login.

**Comment by deanebarker** [comment]
I am not the least bit shocked that their 404 page returns a 200.
