### ISSUE TITLE
Recent Detections

### ISSUE THREAD

**Issue by sggottlieb** [sggottlieb/cmfieldguide#17]
I thought it would be nice to store the results in a database and show them as "Recent Detections" on the landing page. 

We could also use "Recent Detections" for caching.   

The logic would be...

If we have a high confidence of a site, we could list the site and the platform that we think it is.  The list would be reverse chronological.  

What do you think?  Is this a "Beta" feature or a "1.0" feature?  

Maybe we can float the idea on Karla and have her think it through visually?

**Comment by deanebarker** [comment]
I want to do this, but not right now.  Let's get a raw release out there first.
