### ISSUE TITLE
Add is_dot_net method to BaseSignature

### ISSUE THREAD

**Issue by sggottlieb** [sggottlieb/cmfieldguide#2]
This method should return a 1 if we know for sure that the site is running .NET.   If we are not sure, we return a 0.  If we are sure it is not running .NET (don't know how), let's return a -1.

This can be used by Signatures for CMS that run on Java, PHP, or Python to quickly disqualify.  

We discussed  a couple of methods:
- view_state
- Resource.axd
- ct100_

**Comment by deanebarker** [comment]
I created is_dot_net_webforms.  Needs to be refactored a bit based on changes to other methods (overloading page_contains_pattern, for instance).

**Comment by sggottlieb** [comment]
Looks good to me.
