### ISSUE TITLE
Local Page Cache

### ISSUE THREAD

**Issue by deanebarker** [sggottlieb/cmfieldguide#4]
I wonder if we should locally cache retrieved URLs in a dictionary:

{ url, html }

Given a multiplying number of tests, we could be pulling the same pages over and over...

**Comment by deanebarker** [comment]
Like this (on BaseSignature).  I have not tested this.

```
cached_pages = {}

def get_page(self, url):
    if url in self.cached_pages:
        return self.cached_pages[url]

    page = urllib2.urlopen(url, timeout=2)
    self.cached_pages[url] = page

    return page
```

**Comment by deanebarker** [comment]
Although, this still isn't right because this just caches at the Signature level.  I think we should cache at the global level.

**Comment by sggottlieb** [comment]
We could have the engine pass in a pages dictionary that the signatures add to.

**Comment by deanebarker** [comment]
Is there a structure to cache items in the lifecycle of a single request?  (Though, if we Ajax the check, it would be multiple requests, so maybe this wouldn't work.)

I wonder if we don't cache for a timespan, and make it available to multiple requests.  Have a global cache that caches a request for an hour or so, and make it available to anyone testing.  A page isn't likely to change hour by hour.

**Comment by sggottlieb** [comment]
Sounds like you are the one the one who is prematurely optimizing.
Let's start by just caching the pages within a single request so all
of the test can use the cached version rather than getting their own.

On Fri, Mar 16, 2012 at 9:07 AM, deanebarker
reply@reply.github.com
wrote:

**Comment by deanebarker** [comment]
Agreed, I am prematurely optimizing.

So, how do you cache for a single request?  We need to move "outside" the BaseSignature class.

**Comment by sggottlieb** [comment]
Put the pages dictionary in the Engine (which loops through).  Add it
as an argument to the "run" method of BaseSignature and have
BaseSignature pass it back on the return.  Then Engine passes the
collection to another Signature on the next loop.

I am trying to remember if you even need to get the dictionary back.
You may not because everything is by reference.  I would try that
method first.  You can look at it in action using pdb.

On Fri, Mar 16, 2012 at 9:42 AM, deanebarker
reply@reply.github.com
wrote:

**Comment by sggottlieb** [comment]
Complete.  This is basically a subclass of dictionary that overrides the **getitem** method.  You ask the dictionary for a page (by url) and it either returns a cached version or it caches a version and returns that.
