### ISSUE TITLE
Octopress

### ISSUE THREAD

**Issue by winhamwr** [sggottlieb/cmfieldguide#44]
To detect any octropress site that doesn't have a completely-custom theme (not sure if those are detectable), look for the javascript file: `/javascripts/octopress.js`

**Comment by winhamwr** [comment]
To test, http://www.policystat.com should show up as using octopress.

**Comment by sggottlieb** [comment]
Fixed

**Comment by winhamwr** [comment]
Is this code up on http://www.cmfieldguide.com?

The octopress site itself passes ok:
http://www.cmfieldguide.com/detect/?url=http%3A%2F%2Foctopress.org&force=on

But another site running the default octopress theme isn't passing:
http://www.cmfieldguide.com/detect/?url=http%3A%2F%2Fwww.policystat.com&force=on

Just glancing at the code at https://github.com/sggottlieb/cmfieldguide/blob/master/cmfieldguide/cmsdetector/signatures/octopress.py , www.policystat.com/javascripts/octopress.js does indeed contain `getNav`, so I'm a bit confused on why it's not being detected. 

Interestingly, http://www.cmfieldguide.com/detect/?url=http%3A%2F%2Fpolicystat.com&force=on does show as octopress (no www in the URL). There's a 301 redirect from www.policystat.com to policystat.com (using wwwizer, which is useful when you want to host a static site on a service like S3 that can only use CNAME DNS entries), so perhaps that's not being followed?

**Comment by sggottlieb** [comment]
This is great feedback. I will get on it ASAP.

**Comment by sggottlieb** [comment]
suspect that the concatenation is causing a double '/': '//'

Try trimming the last '/' of the end of site URL
