### ISSUE TITLE
MODX Signature Invalid

### ISSUE THREAD

**Issue by jaygilmore** [sggottlieb/cmfieldguide#49]
Seth, 

Your MODX Signature detection is invalid. There are no signatures output by MODX that are standard to an install. The only possible measure is the number of people using the default location of the manger directory and since it can actually live outside webroot and be renamed on install this will not work. MODX.com uses cache busting variables on the css in order to manage versions and ensure css changes get propogated to browsers but this is a design decision and not a function of MODX.

We've had others wanting to collect similar in the past and Netcraft was only able to get approximate counts as we don't have any tracing or metric data on individual websites. This is an architectural decision to obscure version and app version. In fact it would be trivial to make MODX mimic many of the output and path derived  sigs on this cmfieldguide.

**Comment by sggottlieb** [comment]
Hi Jay,

Thanks for the feedback.  

/Seth
