### ISSUE TITLE
Page vs. Url?

### ISSUE THREAD

**Issue by deanebarker** [sggottlieb/cmfieldguide#6]
For consistency, what are we going to call HTML returned from a URL?  A "page"?  And the "url" is just the string that starts "http://..."

If so, then this seems wrong:

```
url_exists
```

Of course the URL exists -- it's just a text string, and it's passed in.  Shouldn't it be "page_exists"?

**Comment by sggottlieb** [comment]
I agree.

**Comment by deanebarker** [comment]
Created a wiki page for definitions:

https://github.com/sggottlieb/cmfieldguide/wiki/Definitions
