### ISSUE TITLE
When is the __init__.py of a package run?

### ISSUE THREAD

**Issue by deanebarker** [sggottlieb/cmfieldguide#7]
Tell me about /signatures/__init__.py.

When is this code run?

**Comment by deanebarker** [comment]
From your email:

> Because it contains the superclass BaseSignature, it is run with a subclass is initialized.

I understand that a class will run its superclass, but when is the specific "class" command run to define the BaseSignature class?  Put another way, when I instantiate a signature like this:

```
class Signature(BaseSignature):
```

Why don't I get a "what the hell is BaseSignature" error?  I don't see that __init__.py gets imported anywhere, but that file must get magically execute somehow.

**Comment by sggottlieb** [comment]
It gets imported here:

```
from cmfieldguide.cmsdetector.signatures import BaseSignature
```

You can think of __init__ as a default module in a package (folder).  

Also, the existence of __init__ tells Python that this folder is a Python package.
