### ISSUE TITLE
How do you overload a function Pythonically?

### ISSUE THREAD

**Issue by deanebarker** [sggottlieb/cmfieldguide#8]
It would be nice if page_contains_pattern could take either a string (a single pattern) or a list (multiple patterns).  If a list, it would test for _any_ of the patterns.  This would avoid multiple calls to the same method, if you have a number of patterns you want to check and you don't really care _which_ one matches, just so long as one of them does.

I'm thinking of this while I'm writing this code:

```
    pattern = 'id="aspnetform"'
    if page_contains_pattern(url, pattern):
        result = True

    pattern = 'ct100_'
    if page_contains_pattern(url, pattern):
        result = True
```

I don't care which one of these returns, so long as one of them does.

But, with no static typing, how do you do this?  Do you just check inside the method to see if the argument is a string or a list?  I know this would work, but I just want to make sure I do it Pythonically.

**Comment by sggottlieb** [comment]
You could do it that way.  Or you could always take a tuple (or list) and iterate through.  In the case of a single pattern, it would just loop through once.

**Comment by deanebarker** [comment]
But can you still pass in a string? Can you still do this:

```
page_contains_pattern(url, 'deane')
```

Or do you have to do this now (note the trailing comma):

```
page_contains_pattern(url, 'deane',)
```

**Comment by sggottlieb** [comment]
You would do:

```
page_contains_pattern(url, ('deane',)):
```

**Comment by deanebarker** [comment]
Is it Pythonic to require this?  In .Net, we would do something like this:

```
Do(string[] arrayOfStrings) { ... }

Do(string singleString)
{
     Do(new string[] { singleString };
}
```

So, the caller can send either a string or an array of strings and get the same thing back.  In Python, do you do things like this?

**Comment by sggottlieb** [comment]
I would just always ask for the tuple.  But I see that the Python Mailer takes either a single To or a List.  Here is how it works.

```
 if isinstance(self.To, basestring):
     msg['To'] = self.To
 else:
      self.To = list(self.To)
      msg['To'] = ", ".join(self.To)
```

**Comment by deanebarker** [comment]
I envision something like this:

```
def do(argument):
    if argument is not list:
        argument = (argument),
    #continue here
```

**Comment by sggottlieb** [comment]
With your "do" I am having Struts flashbacks.

To answer your question.  meh.

On Fri, Mar 16, 2012 at 9:05 AM, deanebarker
reply@reply.github.com
wrote:

**Comment by deanebarker** [comment]
Well, take your "meh" and make page_contains_pattern use a list, then.  It will save lots of code.

**Comment by sggottlieb** [comment]
I would just do what the python mailer does.

On Fri, Mar 16, 2012 at 9:43 AM, deanebarker
reply@reply.github.com
wrote:

**Comment by sggottlieb** [comment]
I added two methods:

contains_any_pattern and contains_all_patterns.  

Methods take a iterable of pattern strings.
