### ISSUE TITLE
Should we just be checking the site as a whole or the submitted URL with path?

### ISSUE THREAD

**Issue by deanebarker** [sggottlieb/cmfieldguide#9]
This code is a problem:

```
if self.page_contains_pattern(self.get_url_stem(url) + '/wp-login.php', 'loginform'):
```

I tried it on deanebarker.net and it didn't work.  Then I realized that my WordPress blog is at deanebarker.net/blog, which means the login page is deanebarker.net/blog/wp-login.php.

We need to account for CMS installs not at the root of the site.  More generally, do we accept that if the submitter enters a URL with a path on it, that he wants to check for the CMS _at that specific path_, not necessarily for the site as a whole?

**Comment by sggottlieb** [comment]
I think we can solve this by adding:

```
elif self.page_contains_pattern(url + '/wp-login.php', 'loginform'):
```

**Comment by deanebarker** [comment]
I agree with can fix this one, but the larger question still stands: if the user submits a domain with path, are we taking them at their word, or should we assume the site as a whole?

**Comment by sggottlieb** [comment]
Now we are getting into a major philosophical discussion of what is a site.  For example is http://www.smith.edu/artmuseum its own site or is it part of http://www.smith.edu.  BTW, http://www.smith.edu is running on Drupal.  http://www.smith.edu/artmuseum is on eZ.

My preference is to say that the site is .edu and that it is running both.  We should allow for two Platforms to have a confidence of 100.

**Comment by deanebarker** [comment]
I'm fine with this.
